### ISSUE TITLE
Generated prescription do not match the expected schema

### ISSUE THREAD

**Issue by codificat** [thoth-station/prescriptions-refresh-job#205]
**Describe the bug**

Currently, this job is generating prescriptions that do not match the [schema](https://github.com/thoth-station/adviser/blob/master/thoth/adviser/prescription/v1/schema.py)

**To Reproduce**

See PRs generated by recent executions of this job, for example https://github.com/thoth-station/prescriptions/pull/38943/files

**Expected behavior**

Prescriptions generated by this job should not fail validation

**Screenshots**

The prescription file referenced above:

``` yaml
units:
  wraps:
  - name: PydeconzGitHubURLWrap
    type: wrap
    should_include:
      adviser_pipeline: true
    match:
      state:
        resolved_dependencies:
        - name: pydeconz
    run:
      justification:
      - type: INFO
        message: Package 'pydeconz' is hosted on GitHub
        link: https://github.com/Kane610/deconz
        package_name: pydeconz
        metadata:
        - prescriptions_repository: git@github.com:thoth-station/prescriptions.git
          prescriptions_version: 0.8.0
```

Note that the metadata is not in the location expected by the schema.

**Additional context**

Prescription metadata was introduced in #155.

Currently, the prescriptions in the prescription repo do not match validation. thoth-adviser is stuck at using [v0.22.0](https://github.com/thoth-station/prescriptions/releases/tag/v0.22.0). See https://github.com/thoth-station/adviser/issues/2402
